### ISSUE TITLE
No WiFi Manager Menu after install

### ISSUE THREAD

**Issue by KD5FMU** [pcpackrat/ASL3-AutoHotSpot#2]
Hello, 

I have ran through the install from the GitHub page and reboot several time but but WIFi manager option ever appears in the left column of the Cockpit in ASL3. Does the node need to be completely devoid of Internet service for this to happen?

**Comment by pcpackrat** [comment]
Sorry, i messed up the script in a late night change and just noticed today when I went to build another node.  

In /var/www there is an autohotspot file.  You will need to rename that to wifisetup.py and then create the directory autohotspot and move it in there.  Then chmod +x the wifisetup.py

commands needed to do the above:

cd /var/www
mv autohotspot wifisetup.py
mkdir autohotspot
mv wifisetup.py autohotspot
cd autohotspot
chmod +x wifisetup.py

**Comment by pcpackrat** [comment]
This does not add wifi manager to cockpit.  Not sure why that was expected.  This just sets up automatic wifi when no network is detected.
